<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Legacy.Core\Legacy.Core.csproj" />
    <PackageReference Include="NLog" Version="5.3.0" />
    <Reference Include="Example.Native, Version=2.1.0.0, Culture=neutral">
      <HintPath>..\ExternalLibraries\Example.Native.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
