name: Tag on Version Change

on:
  push:
    branches:
      - main

jobs:
  tag-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to access previous commits

      - name: Check if pyproject.toml changed
        id: pyproject_changed
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q pyproject.toml; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Get previous version
        if: steps.pyproject_changed.outputs.changed == 'true'
        run: |
          git show HEAD^:pyproject.toml | grep -E '^version' | head -1 | sed 's/version = //' | tr -d "'\"" > old_version.txt

      - name: Get new version
        if: steps.pyproject_changed.outputs.changed == 'true'
        run: |
          grep -E '^version' pyproject.toml | head -1 | sed 's/version = //' | tr -d "'\"" > new_version.txt

      - name: Compare versions and tag
        if: steps.pyproject_changed.outputs.changed == 'true'
        run: |
          old=$(cat old_version.txt)
          new=$(cat new_version.txt)
          if [ "$old" != "$new" ]; then
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git tag "$new"
            git push origin "$new"
          fi
